
---
apiVersion: v1
kind: Secret
metadata:
  name: ${CI_PROJECT_NAME}-secret
  namespace: services
type: Opaque
data:
  VITE_API_BASE: "L2FwaS9iMjQtbGVhZC5waHA="
  B24_BASE: "aHR0cHM6Ly9iaXRyaXguaXRzb3VyY2Uua2cvcmVzdC80MzUvanMyc2J3MTEyeGYweGI2dS8="
  ALLOWED_ORIGINS: "aHR0cHM6Ly9pdHNvdXJjZS5rZyxodHRwczovL3d3dy5pdHNvdXJjZS5rZyxodHRwOi8vbG9jYWxob3N0OjUxNzMsaHR0cDovLzEyNy4wLjAuMTo1MTczLGh0dHBzOi8vY2c0MzgxNC50dzEucnUv"
  TURNSTILE_SECRET: "MHg0QUFBQUFBQjBQNDR4T28wSVNycHBqV2RFYUJKT0JVMk0="
  VITE_TURNSTILE_SITE_KEY: "MHg0QUFBQUFBQjBQNDRDZmN5WDZUNFRH"

